name: gg_image_tools
description: Various tools for image organization. They help to organize folders with images
version: 1.0.0
repository: https://github.com/inlavigo/gg_image_tools

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  exif: ^3.3.0
  path: ^1.8.0

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  pana: ^0.22.0
  test: ^1.24.0
  yaml: ^3.1.2
