name: gg_image_tools
description: Various tools for image organization. They help to organize folders with images
version: 1.0.3
repository: https://github.com/inlavigo/gg_image_tools

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  exif: ^3.3.0
  gg_args: ^2.0.2
  path: ^1.8.0
  recase: ^4.1.0

dev_dependencies:
  test_api: ^0.7.0
  coverage: ^1.7.2
  lints: ^3.0.0
  test: ^1.24.0
  yaml: ^3.1.2
  dart_ping: ^9.0.1
  gg_capture_print: ^1.0.2
  gg_console_colors: ^2.1.4
